
const ActionTypes = {
    CLEAR_SLIP: 'CLEAR_SLIP',
    SET_TOTAL_COST: 'SET_TOTAL_COST',
    SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',
    SET_ERROR_VALUE: 'SET_ERROR_VALUE',
    PUT_QUIZ: 'PUT_QUIZ',
    REPLACE_QUIZ: 'REPLACE_QUIZ',
    FILTER_QUIZ: 'FILTER_QUIZ',
    CHANGE_QUIZ_OP: 'CHANGE_QUIZ_OP',
    UPDATE_QUIZ_ODD: 'UPDATE_QUIZ_ODD',
    DELETE_QUIZ: 'DELETE_QUIZ',
    SET_USE_BONUS: 'SET_USE_BONUS',
    CALCULATE_TOTAL_COST: 'CALCULATE_TOTAL_COST'
}

export default ActionTypes;